# Generated by Django 5.1.3 on 2024-11-18 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ALIMENTOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_alimento', models.CharField(max_length=20)),
                ('tipo_alimento', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PROGRESOS_NUTRICION',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('status_desayuno', models.BooleanField(default=True)),
                ('status_almuerzo', models.BooleanField(default=True)),
                ('estatus_cena', models.BooleanField(default=True)),
                ('dia_completado', models.BooleanField(default=True)),
                ('fecha_ult_actualizacion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='RECETAS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_receta', models.CharField(max_length=50)),
                ('categoria', models.CharField(max_length=20)),
                ('instrucciones', models.TextField()),
                ('objetivo_relacionado', models.CharField(max_length=50)),
                ('imagen', models.ImageField(upload_to='imagenes/')),
            ],
        ),
        migrations.CreateModel(
            name='RECETAS_ALIMENTOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alimento_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Nutricion.alimentos')),
                ('receta_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Nutricion.recetas')),
            ],
        ),
    ]
