# Generated by Django 5.1.3 on 2024-11-18 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EJERCICIOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ejercicio', models.CharField(max_length=20)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(upload_to='imagenes/')),
                ('repeticiones', models.IntegerField()),
                ('series', models.IntegerField()),
                ('descanso_ideal', models.CharField(max_length=20)),
                ('objetivo_relacionado', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PROGRESOS_ENTRENAMIENTO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana_del_anio', models.PositiveIntegerField()),
                ('anio', models.PositiveIntegerField()),
                ('rutina_1', models.BooleanField(default=True)),
                ('rutina_2', models.BooleanField(default=True)),
                ('rutina_3', models.BooleanField(default=True)),
                ('semana_completada', models.BooleanField(default=True)),
                ('decha_ult_actualizacion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='RUTINAS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_rutina', models.CharField(max_length=20)),
                ('objetivo_relacionado', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RUTINA_EJERCICIOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completado', models.BooleanField(default=True)),
                ('ejercicio_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Entrenamiento.ejercicios')),
                ('rutina_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Entrenamiento.rutinas')),
            ],
        ),
    ]
