# Generated by Django 5.1.3 on 2024-11-18 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Entrenamiento', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PROGRESOS_ENTRENAMIENTO',
        ),
    ]
