# Generated by Django 5.1.3 on 2024-11-18 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entrenamiento', '0002_delete_progresos_entrenamiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rutina_ejercicios',
            name='completado',
            field=models.BooleanField(default=False),
        ),
    ]
