# Generated by Django 5.1.3 on 2024-11-18 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='USUARIOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('objetivo', models.CharField(max_length=100)),
                ('correo', models.CharField(max_length=100)),
                ('contrasenia', models.CharField(max_length=100)),
                ('fecha_asig_rutina', models.DateField()),
                ('fecha_asig_recetas', models.DateField()),
            ],
        ),
    ]
