# Generated by Django 5.1.3 on 2024-11-18 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entrenamiento', '0002_delete_progresos_entrenamiento'),
        ('Nutricion', '0002_delete_progresos_nutricion'),
        ('Usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='receta_almuerzo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Almuerzo', to='Nutricion.recetas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuarios',
            name='receta_cena',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='Cena', to='Nutricion.recetas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuarios',
            name='receta_desayuno',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='Desayuno', to='Nutricion.recetas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuarios',
            name='rutina_dia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Entrenamiento.rutinas'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PROGRESOS_ENTRENAMIENTO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana_del_anio', models.PositiveIntegerField()),
                ('anio', models.PositiveIntegerField()),
                ('rutina_1', models.BooleanField(default=True)),
                ('rutina_2', models.BooleanField(default=True)),
                ('rutina_3', models.BooleanField(default=True)),
                ('semana_completada', models.BooleanField(default=True)),
                ('fecha_ult_actualizacion', models.DateField()),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuario.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='PROGRESOS_NUTRICION',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('status_desayuno', models.BooleanField(default=True)),
                ('status_almuerzo', models.BooleanField(default=True)),
                ('status_cena', models.BooleanField(default=True)),
                ('dia_completado', models.BooleanField(default=True)),
                ('fecha_ult_actualizacion', models.DateField()),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuario.usuarios')),
            ],
        ),
    ]
